### ISSUE TITLE
Cygwin build failed running valac with "Package `config' not found ..."

### ISSUE THREAD

**Issue by BrianInglis** [toddy15/libisocodes#1]
Upgrading *Cygwin* `libisocodes` from 1.2.2 to 1.2.4 the build failed when running `valac`: 
```
/usr/bin/valac  --pkg libxml-2.0 --pkg gee-0.8 --library=libisocodes --vapidir=vapi --pkg config --header=libisocodes.h --gir=libisocodes-1.2.4.gir -C .../cygwin/libisocodes/libisocodes-1.2.4-1.x86_64/src/libisocodes-libisocodes-1.2.4/src/isocodes.vala ... .../cygwin/libisocodes/libisocodes-1.2.4-1.x86_64/src/libisocodes-libisocodes-1.2.4/src/exceptions.vala
error: Package `config' not found in specified Vala API directories or GObject-Introspection GIR directories
```
What is the build looking for here - already tried *pickaxe* installs of any *Vala* and *GIR* packages hinting at *conf* or *dev*: 
* libgee-devel libvala0.3{0,4,6,8}-devel
* vala vala-gee{0.8,1.0} vala-dconf
* girepository-GConf2.0

*Cygwin* runs on `newlib` not `glibc` and tries to be *POSIX* and *Linux* compatible with hints of *BSD* and *Solaris* history.

**Comment by lemniscati** [comment]
Modifying the option `--vapidir=vapi` to `--vapidir=$(srcdir)/vapi` will help.

https://github.com/toddy15/libisocodes/blob/libisocodes-1.2.4/Makefile.am#L60
